##Spring Configuration
server:
  port: 8080
spring:
  application:
    name: CarritoCompra
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: /h2
  profiles:
    include:
    active: local   # dev o local (puedes sobreescribir por arg/env)
openai:
  api:
    key: YOUR_OPENAI_API_KEY
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://173.249.41.159:3306/futuredb?serverTimezone=UTC&useSSL=false
    username: remoteuser
    password: my801521my
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none   # update/validate/none
    show-sql: true
    open-in-view: false

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/futuredb?serverTimezone=UTC&useSSL=false
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
